### ISSUE TITLE
Please add `LICENSE`

### ISSUE THREAD

**Issue by penyuan** [thpoll83/PolyKybd#1]
Just discovered this amazing project [from Crowd Supply](https://www.crowdsupply.com/polykybd/polykybd). Thank you @thpoll83 for publishing the hardware and software!

I see on the Crowd Supply page that this project is "Proudly Open Source", fantastic! However, there is no open source license associated with this repository, which makes it not fit the [Open Source Hardware definition](https://www.oshwa.org/definition/). Fortunately, [this is easy to add](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository), and there are [open source **hardware** licenses](https://choosealicense.com/non-software/) to choose from such as the [CERN-OHL-S-2.0](https://choosealicense.com/licenses/cern-ohl-s-2.0/).

Can the maintainer(s) please add an open source hardware `LICENSE` to this repository? Thanks!

**Comment by thpoll83** [comment]
Sure, will do~

**Comment by penyuan** [comment]
> Sure, will do~

Thanks @thpoll83! Looking forward to seeing an open source hardware `LICENSE` in this repository. 😄

**Comment by thpoll83** [comment]
Done~
