### ISSUE TITLE
Was interested in this project, but can't find schematics in readable format

### ISSUE THREAD

**Issue by trollcop** [thpoll83/PolyKybd#3]
I'm not really interested in installing kicad, is there any reason why schematics in PDF aren't provided? Was driving by the project and was curious how you'd have ~80 SPI LCD chip selects managed but the curiosity was not enough to warrant installing something to view it.

**Comment by thpoll83** [comment]
It is a KiCad project (as mentioned in the readme), just install and open the schematics. For PDF I have to change binary files for every revision...
