### ISSUE TITLE
Darkened keycaps

### ISSUE THREAD

**Issue by michaelblyons** [thpoll83/PolyKybd#5]
We need to get AncientJames' resin cast keycaps. 😜 I'm half joking and half serious. It might blur smaller icons unacceptably.

It's great that the transparent cash register caps are widely available, but an upgrade (if possible) to shaped keycaps would be awesome in the longer term.

Love the project! Keep it up!

**Comment by thpoll83** [comment]
Thanks, I would say everyone is free to make some resin casts. It's unfortunately nothing I can mass-produce. Also replacing screens would be impossible.
So yeah, go for it if you like it and if you are able to do so. Otherwise, be my guest and use the transparent keycaps

**Comment by michaelblyons** [comment]
No worries!

Related: I talked to a wood veneer supplier to ask about adding 0.x mm wood sheets to the keys. They said the shine-through would depend on a bunch of factors, from the wood selected, the OLED brightness, and the adhesive (if any). When you ship kits, I may try it out.

Best of luck with the project!
